const $ = id => document.getElementById(id);
const COLAB_URL='https://colab.research.google.com/github/hol201/photo-to-video/blob/main/notebooks/cogvideox-i2v-colab.ipynb';
const input=$('imageInput'), drop=$('dropzone'), preview=$('preview'), empty=$('emptyUpload'), wrap=$('previewWrap'); let imageData='';
function setStatus(text,type=''){const s=$('status');s.textContent=text;s.className='status '+type}
function loadFile(file){if(!file)return;if(file.size>5*1024*1024)return setStatus('Файл больше 5 МБ. Выберите изображение меньшего размера.','error');if(!file.type.startsWith('image/'))return setStatus('Поддерживаются PNG, JPG и WEBP.','error');const r=new FileReader();r.onload=()=>{imageData=r.result;preview.src=imageData;empty.classList.add('hidden');wrap.classList.remove('hidden');$('fileLabel').textContent=file.name};r.readAsDataURL(file)}
$('chooseButton').onclick=()=>input.click();input.onchange=()=>loadFile(input.files[0]);$('removeImage').onclick=()=>{imageData='';input.value='';wrap.classList.add('hidden');empty.classList.remove('hidden');setStatus('')};
['dragenter','dragover'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.style.borderColor='var(--accent)'}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.style.borderColor=''}));drop.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));
$('prompt').oninput=e=>$('counter').textContent=`${e.target.value.length} / 1000`;
$('colabButton').onclick=()=>{if(!imageData)return setStatus('Сначала выберите фотографию. Затем загрузите её в открывшемся Colab.','error');const p=$('prompt').value.trim();if(p){localStorage.setItem('photo_motion_prompt',p)}window.open(COLAB_URL,'_blank');setStatus('Colab открыт. Запустите ячейки сверху вниз и загрузите туда фотографию.','success')};
$('runwayButton').onclick=()=>document.querySelector('.settings-panel').open=true;
const stored=localStorage.getItem('runway_api_key');if(stored)$('apiKey').value=stored;$('saveKey').onclick=()=>{const k=$('apiKey').value.trim();if(!k)return setStatus('Введите API-ключ.','error');localStorage.setItem('runway_api_key',k);$('keySaved').textContent='Сохранено в этом браузере';setTimeout(()=>$('keySaved').textContent='',2500)};
