const $ = id => document.getElementById(id);
const input=$('imageInput'), drop=$('dropzone'), preview=$('preview'), empty=$('emptyUpload'), wrap=$('previewWrap');
let imageData='';
function setStatus(text, type=''){const s=$('status');s.textContent=text;s.className='status '+type}
function loadFile(file){if(!file)return;if(file.size>5*1024*1024)return setStatus('Файл больше 5 МБ. Выберите изображение меньшего размера.','error');if(!file.type.startsWith('image/'))return setStatus('Поддерживаются PNG, JPG и WEBP.','error');const r=new FileReader();r.onload=()=>{imageData=r.result;preview.src=imageData;empty.classList.add('hidden');wrap.classList.remove('hidden');$('fileLabel').textContent=file.name};r.readAsDataURL(file)}
$('chooseButton').onclick=()=>input.click();input.onchange=()=>loadFile(input.files[0]);$('removeImage').onclick=()=>{imageData='';input.value='';wrap.classList.add('hidden');empty.classList.remove('hidden');setStatus('')};
['dragenter','dragover'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.style.borderColor='var(--accent)'}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.style.borderColor=''}));drop.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));
$('prompt').oninput=e=>$('counter').textContent=`${e.target.value.length} / 1000`;
const stored=localStorage.getItem('runway_api_key');if(stored)$('apiKey').value=stored;$('saveKey').onclick=()=>{const k=$('apiKey').value.trim();if(!k)return setStatus('Введите API-ключ.','error');localStorage.setItem('runway_api_key',k);$('keySaved').textContent='Сохранено в этом браузере';setTimeout(()=>$('keySaved').textContent='',2500)};
async function generate(){const key=$('apiKey').value.trim()||localStorage.getItem('runway_api_key');const prompt=$('prompt').value.trim();if(!imageData)return setStatus('Сначала добавьте фотографию.','error');if(!prompt)return setStatus('Добавьте описание движения.','error');if(!key)return setStatus('Откройте «Настройки API» и добавьте Runway API key.','error');const btn=$('generateButton');btn.disabled=true;setStatus('Отправляем кадр в Runway…');try{const res=await fetch('https://api.dev.runwayml.com/v1/image_to_video',{method:'POST',headers:{Authorization:`Bearer ${key}`,'X-Runway-Version':'2024-11-06','Content-Type':'application/json'},body:JSON.stringify({model:'gen4_turbo',promptText:prompt,promptImage:imageData,ratio:$('ratio').value,duration:Number($('duration').value)})});const data=await res.json();if(!res.ok)throw new Error(data.message||data.error||`Ошибка API (${res.status})`);setStatus(`Задание ${data.id||''} создано. Проверяем готовность…`);await poll(data.id,key)}catch(e){setStatus(e.message.includes('Failed to fetch')?'Браузер заблокировал запрос. Для рабочего режима нужен серверный прокси с ключом.':e.message,'error')}finally{btn.disabled=false}}
async function poll(id,key){for(let i=0;i<60;i++){await new Promise(r=>setTimeout(r,5000));const res=await fetch(`https://api.dev.runwayml.com/v1/tasks/${id}`,{headers:{Authorization:`Bearer ${key}`,'X-Runway-Version':'2024-11-06'}});const d=await res.json();if(d.status==='SUCCEEDED'){const url=d.output?.[0]||d.output?.video_url;if(url){setStatus('Видео готово — откройте результат ниже.','success');const a=document.createElement('a');a.href=url;a.target='_blank';a.className='result-link';a.textContent='▶ Открыть готовое видео';$('status').appendChild(document.createElement('br'));$('status').appendChild(a);return}}if(d.status==='FAILED'||d.status==='CANCELED')throw new Error(d.failure||'Генерация не удалась.')}throw new Error('Генерация занимает дольше обычного. Проверьте результат позже в Runway.')}
$('generateButton').onclick=generate;
